[package]
name = "TokenMinter"
version = "1.0.0"
authors = []
upgrade_policy = "immutable"

[addresses]
minter = "_"
migration = "0x1c5acf62be507c27a7788a661b546224d806246765ff2695efece60194c6df05"
# Mock addresses for testing.
minter_v2 = "0x999"

[dev-addresses]
minter = "0x123"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token-objects'

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'dev'
subdir = 'aptos-move/framework/aptos-token'

[dev-dependencies]
